//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime Deadline { get; set; }
        public int UserReceipt { get; set; }
        public int DeviceType { get; set; }
        public int BrandDevice { get; set; }
        public string ModelDevice { get; set; }
        public int Client { get; set; }
        public decimal Price { get; set; }
        public string Malfunction { get; set; }
        public System.DateTime ReceiptTime { get; set; }
        public string AppearanceDevice { get; set; }
        public string Equipment { get; set; }
        public byte[] FileData { get; set; }
    
        public virtual BrandDevice BrandDevice1 { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual DeviceType DeviceType1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
