//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWriteOff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductWriteOff()
        {
            this.ProductWriteOffHistory = new HashSet<ProductWriteOffHistory>();
        }
    
        public int WriteOffID { get; set; }
        public System.DateTime Date { get; set; }
        public int WriteUser { get; set; }
        public int WriteWarehouse { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
        public virtual WarehouseService WarehouseService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWriteOffHistory> ProductWriteOffHistory { get; set; }
    }
}
