//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Articule { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Price { get; set; }
        public string MaxDiscount { get; set; }
        public int ManufactureID { get; set; }
        public int ProvideID { get; set; }
        public int CategoryID { get; set; }
        public string DiscountNow { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual Provide Provide { get; set; }
    }
}
