//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWriteOffHistory
    {
        public int ProductHistoryWriteID { get; set; }
        public int ProductW { get; set; }
        public int ProductWQuantity { get; set; }
        public int ProductWriteOff { get; set; }
    
        public virtual ProductWriteOff ProductWriteOff1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
