//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationProduct()
        {
            this.ProductRemnants = new HashSet<ProductRemnants>();
        }
    
        public int RegistrationID { get; set; }
        public System.DateTime Date { get; set; }
        public string InvoiceNumber { get; set; }
        public int RegUser { get; set; }
        public int RegClient { get; set; }
        public int RegWarehouse { get; set; }
        public int RegProduct { get; set; }
        public string Note { get; set; }
        public decimal RegAmount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRemnants> ProductRemnants { get; set; }
        public virtual User User { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
